#! /bin/sh

set -e

DEFAULT_DPI=96
DPI=158
#DEVICE_SCALE_FACTOR=$((DPI / DEFAULT_DPI))
DEVICE_SCALE_FACTOR=1.65

exec /usr/bin/chromium --force-device-scale-factor=$DEVICE_SCALE_FACTOR \
                       --enable-dom-distiller "$@"
