#! /usr/bin/env python3

'''
Print files given on CLI (or as lines in stdin) that don't end in a newline

UNIX says text files' final line should have a \\n.
'''

from sys import argv, stdin
from pathlib import Path


for arg in argv[1:] or (line[:-1] for line in stdin):
    try:
        if Path(arg).read_text()[-1] != '\n':
            print(arg)
    except (UnicodeDecodeError, IndexError):
        pass
