#! /usr/bin/env python3

from argparse import ArgumentParser
from sys import argv
from os import fstat, sendfile


argument_parser = ArgumentParser(description='Kernel-side copy of files')
argument_parser.add_argument('source_file')
argument_parser.add_argument('destination_file')


args = argument_parser.parse_args()
try:
    with open(args.source_file, 'rb') as source_file, \
         open(args.destination_file, 'wb') as destination_file:
        size = fstat(source_file.fileno()).st_size
        while size > 0:
            size -= sendfile(destination_file.fileno(),
                             source_file.fileno(),
                             None,
                             size)
except OSError as e:
    argument_parser.exit(status=1,
                         message='{}: {}: {}\n'.format(argv[0],
                                                       e.filename,
                                                       e.strerror))
