#! /usr/bin/env python

import html
import json
import subprocess
from os import environ
from urllib.request import urlopen


_DATA_URL = 'http://weather.gc.ca/wxlink/site_js/s0000430_e.js'


def gc_getitems():
    for varkw, var, eqop, val in (line.rstrip(';')
                                      .split(maxsplit=3)
                                  for line
                                  in urlopen(_DATA_URL).read()
                                                       .decode()
                                                       .splitlines()
                                  if line):
        assert varkw == 'var'
        assert eqop == '='
        yield var, json.loads(val)


def gc_jsonitems(items, indent=4, sort=True):
    print(html.unescape(json.dumps(dict(items), indent=indent, sort_keys=sort)))


def gc_printitems(items):
    d = dict(items)
    # Wind to or from?
    print('{}, {}{}, wind {}Km/h from {}'
          .format(d['obCondition'],
                  d['obTemperature'],
                  ' (wind chill {})'
                    .format(d['obWindChill']) if d.get('obWindChill', False) else '',
                  d['obWindSpeed'], d['obWindDir']))


def gc_gtkitems(items):
    raise NotImplementedError()


def gc_tkitems(items):
    raise NotImplementedError()


def gc_web(items, *args):
    if not args:
        args = [environ['BROWSER']]
    subprocess.check_call(args + [v for k, v in items if k == 'cityURL'])


if __name__ == '__main__':
    from argparse import ArgumentParser
    from os import environ

    ap = ArgumentParser('Government of Canada Ottawa, ON weather feed')
    uis = ap.add_mutually_exclusive_group()
    for ui in 'print', 'json', 'gtk', 'tk', 'web':
        uis.add_argument('--' + ui, dest='ui', action='store_const', const=ui)

    args = ap.parse_args()

    if args.ui is None:
        if 'DISPLAY' in environ:
            try:
                import gi; gi.require_version('Gtk', '3.0')
                from gi.repository import Gtk
                args.ui = 'gtk'
            except ImportError:
                import tkinter
                args.ui = 'tk'
        else:
            args.ui = 'print'

    {
        'json': gc_jsonitems,
        'print': gc_printitems,
        'gtk': gc_gtkitems,
        'tk': gc_tkitems,
        'web': gc_web,
    }[args.ui](gc_getitems())
